### ISSUE TITLE
install

### ISSUE THREAD

**Issue by suavp** [Bolton-and-Menk-GIS/restapi#13]
I cannot get it to run in both python2 or python3 on Mac. 
python 3.6 I get the following error
    from common_types import *
ModuleNotFoundError: No module named 'common_types'

python 2 I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/restapi/__init__.py", line 12, in <module>
    from common_types import *
  File "/usr/local/lib/python2.7/site-packages/restapi/common_types.py", line 9, in <module>
    from rest_utils import *
  File "/usr/local/lib/python2.7/site-packages/restapi/rest_utils.py", line 76, in <module>
    TEMP_DIR = os.environ['TEMP']
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'TEMP'

**Comment by CalebM1987** [comment]
Thank you for bringing this to my attention.  I have never tested on my mac, but this error appears to be an os specific issue because I think that ```os.environ['TEMP']``` is only available on Windows.  I am actually preparing to update this package to be compatible with Python 2 and 3 and I think I will use the ```tempfile``` module to work with temporary files and directories, which should work on OSX as well.

I'm going to log this as a bug and will hopefully have a fix in the near future.

**Comment by CalebM1987** [comment]
This was actually fixed a long time ago, but I forgot to close this issue.  The fix I implemented is below:

```py
# temp dir for json outputs
TEMP_DIR = tempfile.gettempdir()
if not os.access(TEMP_DIR, os.W_OK| os.X_OK):
    TEMP_DIR = None
```
