### ISSUE TITLE
[bug] JSON_CODE not defined

### ISSUE THREAD

**Issue by sallaben** [Bolton-and-Menk-GIS/restapi#14]
hey there, what is JSON_CODE enum?  when exporting mapserver layer to shapefile I get this error:

    Traceback (most recent call last):
    File "test.py", line 9, in <module>
    layer.layer_to_fc(output)
    File "/usr/local/lib/python2.7/site-packages/restapi/common_types.py", line 1311, in export_layer
    exportFeatureSet(fs, out_fc, outSR=sr)
    File "/usr/local/lib/python2.7/site-packages/restapi/common_types.py", line 289, in exportFeatureSet
    w.add_row(Geometry(feat.geometry).asShape(), row)
    File "/usr/local/lib/python2.7/site-packages/restapi/open_restapi.py", line 358, in asShape
    shp.points = self.json[JSON_CODE[self.geometryType]]
    NameError: global name 'JSON_CODE' is not defined

**Comment by mfandre** [comment]
+1

**Comment by CalebM1987** [comment]
@sallaben Thanks for pointing this out!  Looks like I accidentally deleted the ```JSON_CODE``` dict a while back while cleaning some stuff up.  Luckily I was able to recover this from an old version.  I just tested this as the open source version and it now works again.  Let me know if you have any other issues, thanks!

Sorry for the inconvenience!

**Comment by CalebM1987** [comment]
fixed on July 11th, needed to add the `JSON_CODE` dict back into the code.
