### ISSUE TITLE
AttributeError: 'ArcServer' object has no attribute 'folders'

### ISSUE THREAD

**Issue by pdinkins** [Bolton-and-Menk-GIS/restapi#54]
Traceback (most recent call last):
  File "C:\...\pipeline-env\Lib\site-packages\restapi\rest_utils.py", line 859, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ArcServer' object has no attribute 'folders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\pipeline-env\geo-pipe1\geo_pipe1\serverrequests\serverrequests.py", line 207, in createLYR_INFO_DF
    for root, services in restAPIobject.walk():
  File "C:\...\pipeline-env\Lib\site-packages\restapi\common_types.py", line 1428, in walk
    for f in self.folders:
             ^^^^^^^^^^^^
  File "C:\...\pipeline-env\Lib\site-packages\restapi\rest_utils.py", line 865, in __getattr__
    raise AttributeError(name)
AttributeError: folders

I am not sure what is going on here? Some servers work while others seem to throw this error when trying to get the services available. I tried finding a similar issue in the in the closed issues but maybe I missed something.

**Comment by philnagel** [comment]
Are you able to share a publicly accessible server URL that exhibits this issue?

**Comment by pdinkins** [comment]
Here are a few examples:
https://services5.arcgis.com/6gTxIFMxZdWxCrVQ/arcgis/rest/services
https://services3.arcgis.com/eoLFybJXLOtInQXJ/arcgis/rest/services
https://services1.arcgis.com/HuQMFGE1RTLjFtYd/ArcGIS/rest/services

**Comment by philnagel** [comment]
This should be fixed in version [2.4.5](https://github.com/Bolton-and-Menk-GIS/restapi/releases/tag/2.4.5)

**Comment by pdinkins** [comment]
Testing now and seems to be working. Thank you!
